apiVersion: apps.tachy.one/v1alpha
kind: ComputeApp
metadata:
  name: muon-platform
  tenantId: tn_01m2aam6mcq85h03j3fscq7bvj
spec:
  envVars:
    - name: DATABASE_URL
      type: credential
      value: ""
    - name: RUST_LOG
      value: info
